name: Release

# Controls when the action will run.
on:
  # Triggers the workflow on push events for all branches except master
  push:
    branches-ignore:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Package app
        run: ./package.sh

      - name: Set Variables
        run: |
          echo "APP_NAME=$(<'./.app')" >> "$GITHUB_ENV"
          echo "VERSION=v$(<'./data/version')" >> "$GITHUB_ENV"
          echo "PRERELEASE=$(grep -qE '^0' <'./data/version' && echo 'true' || echo 'false')" >> "$GITHUB_ENV"
          echo "RELEASE=$(curl -sH 'Accept: application/vnd.github.v3+jso' -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/m3l6h/utilities/releases | grep -q "gacp v$(<'./data/version')" && echo 'true' || echo 'false')" >> "$GITHUB_ENV"
          echo "MAKE_TAG=$(git fetch --prune --unshallow && git describe --tags --abbrev=0 --match "v$(<'./data/version')" 'HEAD~' && echo 'false' || echo 'true')" >> "$GITHUB_ENV"

      - name: Create Tag
        uses: negz/create-tag@v1
        if: ${{ env.MAKE_TAG }}
        with:
          version: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@master
        if: ${{ env.RELEASE }}
        with:
          name: "${{ env.APP_NAME }} ${{ env.VERSION }}"
          prerelease: ${{ env.PRERELEASE }}
          body_path: ./CHANGELOG.md
          tag_name: ${{ env.VERSION }}
          files: |
            ./dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
