name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push events for all branches except master
  push:
    branches-ignore: 
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Package app
        run: ./package.sh
        
      - name: Set Variables
        run: |
          echo "name=APP_NAME::$(<'./app')" >> "$GITHUB_ENV"
          echo "name=VERSION::$(<'./data/version')" >> "$GITHUB_ENV"
          echo "name=CHANGELOG::$(<'./CHANGELOG.md')" >> "$GITHUB_ENV"
          echo "name=PRERELEASE::$(grep -qE '^0' <'./data/version' && echo 'true' || echo 'false')" >> "$GITHUB_ENV"

      - name: Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          body: ${{ env.CHANGELOG }}
          name: "${{ env.APP_NAME }} ${{ env.VERSION }}"
          prerelease: ${{ env.PRERELEASE }}
          files: |
            ./dist/*.tar.gz
