name: Release

# Controls when the action will run. 
on:
  # Triggers the workflow on push events for all branches except master
  push:
    branches-ignore: 
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Package app
        run: ./package.sh
        
      - name: Set Variables
        run: |
          echo "APP_NAME=$(<'./.app')" >> "$GITHUB_ENV"
          echo "VERSION=$(<'./data/version')" >> "$GITHUB_ENV"
          echo "PRERELEASE=$(grep -qE '^0' <'./data/version' && echo 'true' || echo 'false')" >> "$GITHUB_ENV"
          
      - name: Query Tag
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          include: ${{ env.VERSION }}
          
      - name: Create Tag
        uses: negz/create-tag@v1
        if: ${{ ! steps.tagger.outputs.tag }}
        with:
          version: ${{ env.VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          name: "${{ env.APP_NAME }} ${{ env.VERSION }}"
          prerelease: ${{ env.PRERELEASE }}
          body_path: ./CHANGELOG.md
          tag_name: ${{ env.VERSION }}
          files: |
            ./dist/*.tar.gz
